# Generated by Django 3.0.8 on 2021-08-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
