# Generated by Django 3.0.8 on 2021-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210828_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
